import {Design} from "./design";

export const DESIGNS : Design[] = [
  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},

  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "레오나르도 다빈치", subject : "황금오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "로댕", subject : "골드덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "황금거위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "이중섭", subject : "금색오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "안견", subject : "노란오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "마네", subject : "옐로덕", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "모네", subject : "골드키위", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "오리구이직전", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},
  { nickName : "달리 벤 피카소", subject : "금빛오리", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg",description : "얘야 오늘은 오리구이가 먹고싶구나"},



]
