import {Design} from "./design";

export const DESIGNS : Design[] = [
  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},

  { nickName : "레오나르도 다빈치", subject : "홍대 디자인과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "로댕", subject : "건대 건축학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "이중섭", subject : "서울대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "안견", subject : "경기대 철학과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "마네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "모네", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"},
  { nickName : "달리 벤 피카소", subject : "연대 조소과", profileImageUrl : "../../assets/image/man.png", designImageUrl:"../../assets/image/duck.jpg"}
]
